"""Shared fixtures.

The golden MATLAB reference is the backbone of this suite: ``tests/data/matlab_reference.mat``
holds inputs *and* the MATLAB implementations' outputs for the same inputs, generated by
``tests/matlab_ref/gen_reference.m``. Committing both means the port is checked against real
MATLAB behaviour on any machine, with no MATLAB installed.
"""

from __future__ import annotations

import os
from pathlib import Path

import numpy as np
import pytest

# Must be set before Qt is imported anywhere: the GUI tests run without a display (and this
# keeps them from stealing focus on a developer's desktop).
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

DATA_DIR = Path(__file__).parent / "data"
REFERENCE_MAT = DATA_DIR / "matlab_reference.mat"


@pytest.fixture(scope="session")
def ref() -> dict:
    """The MATLAB golden reference, with MATLAB's row/column vectors flattened.

    ``scipy.io.loadmat`` returns every 1-D MATLAB array as 2-D (``(1, N)`` or ``(N, 1)``),
    which would make every comparison need its own ``.ravel()``. Squeezing the known-1-D
    entries here keeps the tests about the maths.
    """
    scipy_io = pytest.importorskip("scipy.io")
    if not REFERENCE_MAT.exists():
        pytest.skip(f"{REFERENCE_MAT} missing — regenerate with tests/matlab_ref/gen_reference.m")
    raw = scipy_io.loadmat(str(REFERENCE_MAT))
    out = {k: v for k, v in raw.items() if not k.startswith("__")}

    for key in (
        "t",
        "ela_winSamps",
        "ela_eventTimes",
        "ela_eventLabels",
        "ela_sortedLabels",
        "ela_calcWin",
        "corr_varP",
        "corr_pixel",
        "pixel_trace",
        "schmitt_sig",
        "schmitt_thresh",
        "schmitt_flipTimes",
        "schmitt_flipUp",
        "schmitt_flipDown",
    ):
        if key in out:
            out[key] = np.asarray(out[key]).ravel()
    for key in ("Ypix", "Xpix", "nSV", "T", "Fs"):
        if key in out:
            out[key] = float(np.asarray(out[key]).ravel()[0])
    return out


@pytest.fixture(scope="session")
def synthetic_session(tmp_path_factory) -> Path:
    """A tiny on-disk session in the real server layout, for exercising ``widefield.io``.

    Written Fortran-order with the component axis last, exactly as npy-matlab writes it, so
    the component-prefix read path is genuinely tested rather than bypassed.
    """
    root = tmp_path_factory.mktemp("session")
    rng = np.random.default_rng(0)
    ypix, xpix, nsv, n_frames = 8, 6, 10, 240
    fs = 35.0

    for name, n_this in (("blue", nsv), ("violet", nsv)):
        d = root / name
        d.mkdir()
        u = rng.standard_normal((ypix, xpix, n_this)).astype(np.float32)
        v = rng.standard_normal((n_frames, n_this)).astype(np.float32)
        t = (np.arange(n_frames) / fs)[:, None]
        np.save(d / "svdSpatialComponents.npy", np.asfortranarray(u))
        np.save(d / "svdTemporalComponents.npy", np.asfortranarray(v))
        np.save(d / "svdTemporalComponents.timestamps.npy", np.asfortranarray(t))
        np.save(d / "meanImage.npy", np.asfortranarray(100.0 + rng.random((ypix, xpix))))

    # corr: fewer components than blue's U, and one frame short — both true of real sessions.
    d = root / "corr"
    d.mkdir()
    n_corr = 4
    vc = rng.standard_normal((n_frames - 1, n_corr)).astype(np.float32)
    np.save(d / "svdTemporalComponents_corr.npy", np.asfortranarray(vc))
    np.save(
        d / "svdTemporalComponents_corr.timestamps.npy",
        np.asfortranarray((np.arange(n_frames - 1) / fs)[:, None]),
    )
    return root


@pytest.fixture
def small_uv():
    """A deterministic (U, V) pair with orthonormal U, for maths that assumes an SVD basis."""
    rng = np.random.default_rng(1234)
    ypix, xpix, nsv, n_frames = 9, 7, 5, 300
    q, _ = np.linalg.qr(rng.standard_normal((ypix * xpix, nsv)))
    u = q.reshape(ypix, xpix, nsv)
    v = rng.standard_normal((nsv, n_frames)) * 5.0
    t = np.arange(n_frames) / 35.0
    return u, v, t
