"""SVD-compressed movie primitives.

A widefield movie is stored factored as ``M = U @ V`` (the singular values are folded into
``V``, following the MATLAB convention documented in the top-level README), where

* ``U`` is ``(Ypix, Xpix, nSV)`` — spatial components,
* ``V`` is ``(nSV, nFrames)`` — temporal components.

Everything here is a faithful port of the MATLAB in ``matlab/`` and is validated against
golden reference data generated by ``tests/matlab_ref/gen_reference.m``. Where the MATLAB and
a "more obvious" Python spelling disagree, the MATLAB wins and the difference is commented.

Pure numpy/scipy — no Qt, so this stays importable on a headless machine.
"""

from __future__ import annotations

import numpy as np
from scipy.signal import butter, detrend, filtfilt, lfilter, sosfilt, sosfilt_zi, sosfiltfilt

__all__ = [
    "flatten_u",
    "svd_frame_reconstruct",
    "pixel_timecourse",
    "change_u",
    "dff_from_svd",
    "hp_filt",
    "bandpass_filt",
    "detrend_and_filt",
    "subsample_shift",
    "bin_image",
]


# --------------------------------------------------------------------------------------
# reshaping helpers
# --------------------------------------------------------------------------------------


def flatten_u(u: np.ndarray) -> np.ndarray:
    """``U`` ``(Ypix, Xpix, nSV)`` → ``(nPix, nSV)``, C-contiguous.

    Contiguity matters: every reconstruction is a GEMM/GEMV against this array, and a strided
    or Fortran-ordered view silently costs a full copy inside BLAS on every call instead of
    once here.

    For a C-contiguous ``u`` (what :func:`widefield.io.read_u_from_npy` returns) this is a free
    reshape — no copy — which is what makes it safe to call per frame.
    """
    u = np.asarray(u)
    if u.ndim != 3:
        raise ValueError(f"U must be (Ypix, Xpix, nSV); got shape {u.shape}")
    ypix, xpix, nsv = u.shape
    flat = u.reshape(ypix * xpix, nsv)
    return flat if flat.flags["C_CONTIGUOUS"] else np.ascontiguousarray(flat)


def _aligned_nsv(u: np.ndarray, v: np.ndarray) -> int:
    """Components shared by U and V.

    The hemo-corrected channel's ``V`` is routinely truncated relative to the blue ``U`` it
    borrows, so callers pass mismatched ranks all the time; MATLAB would error, we truncate.
    """
    return min(u.shape[-1], v.shape[0])


# --------------------------------------------------------------------------------------
# reconstruction
# --------------------------------------------------------------------------------------


def svd_frame_reconstruct(u: np.ndarray, v: np.ndarray) -> np.ndarray:
    """Reconstruct frames from the SVD basis. Port of ``svdFrameReconstruct.m``.

    Parameters
    ----------
    u : (Ypix, Xpix, nSV)
    v : (nSV, nFrames) or (nSV,) for a single frame

    Returns
    -------
    (Ypix, Xpix, nFrames), or (Ypix, Xpix) when ``v`` was 1-D.

    Unlike MATLAB, a trailing singleton is only dropped when ``v`` itself was 1-D — so
    ``v[:, [7]]`` reliably gives you ``(Y, X, 1)`` rather than silently collapsing.
    """
    u = np.asarray(u)
    v = np.asarray(v)
    single = v.ndim == 1
    if single:
        v = v[:, None]
    if v.ndim != 2:
        raise ValueError(f"V must be (nSV, nFrames) or (nSV,); got shape {v.shape}")

    nsv = _aligned_nsv(u, v)
    ypix, xpix = u.shape[0], u.shape[1]
    flat = flatten_u(u[..., :nsv])
    out = (flat @ v[:nsv]).reshape(ypix, xpix, v.shape[1])
    return out[..., 0] if single else out


def pixel_timecourse(u: np.ndarray, v: np.ndarray, pixel: tuple[int, int]) -> np.ndarray:
    """One pixel's full timecourse ``(nFrames,)`` — ``U[y, x, :] @ V``.

    ``pixel`` is ``(row, col)`` and **0-based** (the MATLAB is 1-based). Reconstructing a
    single pixel costs O(nSV * nFrames), never the full movie.
    """
    u = np.asarray(u)
    v = np.asarray(v)
    nsv = _aligned_nsv(u, v)
    y, x = int(pixel[0]), int(pixel[1])
    return np.asarray(u[y, x, :nsv]) @ np.asarray(v[:nsv])


# --------------------------------------------------------------------------------------
# basis changes / dF/F
# --------------------------------------------------------------------------------------


def change_u(u: np.ndarray, v: np.ndarray, new_u: np.ndarray) -> np.ndarray:
    """Re-express the movie ``(u, v)`` in a new spatial basis. Port of ``ChangeU.m``.

    Returns ``new_v`` such that ``new_u @ new_v`` approximates ``u @ v``. Exact only when
    ``new_u`` spans ``u``'s column space; that is the case in practice because the callers
    project between two bases of the same movie.
    """
    u, v, new_u = np.asarray(u), np.asarray(v), np.asarray(new_u)
    flat, new_flat = flatten_u(u), flatten_u(new_u)
    if flat.shape[0] != new_flat.shape[0]:
        raise ValueError(
            f"U and newU must have the same pixel count; got {flat.shape[0]} vs {new_flat.shape[0]}"
        )
    # (new_flat.T @ flat) first: an (nSV, nSV) mixing matrix, then one small matmul against V.
    # Grouping the other way would form an (nPix, nFrames) intermediate — the whole movie.
    return (new_flat.T @ flat) @ v


def dff_from_svd(
    u: np.ndarray, v: np.ndarray, mean_image: np.ndarray, soft_norm: float | None = None
) -> tuple[np.ndarray, np.ndarray]:
    """Soft-normalized dF/F, kept in the original ``U`` basis. Port of ``dffFromSVD.m``.

    Dividing each pixel by (mean + soft) breaks orthonormality of ``U``, so the result is
    re-cast into the original basis via :func:`change_u`; only ``V`` changes.

    ``soft_norm`` defaults to ``median(mean_image)``, as in the MATLAB. It keeps low-mean
    pixels (outside the window, vasculature) from exploding when divided by near-zero.

    Returns ``(new_u, new_v)``. ``new_u`` *is* ``u`` — returned for symmetry with the MATLAB,
    whose two-output signature exists to stop callers using a stale single-output version.
    """
    u, v = np.asarray(u), np.asarray(v)
    mean_image = np.asarray(mean_image)
    nsv = _aligned_nsv(u, v)
    u = u[..., :nsv]
    v = v[:nsv]

    flat = flatten_u(u)
    mean_flat = mean_image.reshape(-1)
    if mean_flat.size != flat.shape[0]:
        raise ValueError(f"meanImage has {mean_flat.size} pixels but U has {flat.shape[0]}")

    if soft_norm is None:
        soft_norm = float(np.median(mean_flat))

    # Zero-mean V, then divide U by (mean + soft) and rotate back into the original basis.
    new_v = v - v.mean(axis=1, keepdims=True)
    nonnorm = (flat / (mean_flat[:, None] + soft_norm)).reshape(u.shape)
    return u, change_u(nonnorm, new_v, u)


# --------------------------------------------------------------------------------------
# temporal filtering
# --------------------------------------------------------------------------------------


# MATLAB's filtfilt pads by 3*(nfilt-1) with an odd reflection. scipy defaults to
# padlen=3*max(len(a), len(b)), which is one sample longer and gives visibly different
# edges — so every filtfilt here passes MATLAB's padlen explicitly.
def _matlab_filtfilt(b: np.ndarray, a: np.ndarray, x: np.ndarray, axis: int = -1) -> np.ndarray:
    padlen = 3 * (max(len(a), len(b)) - 1)
    return filtfilt(b, a, x, axis=axis, padtype="odd", padlen=padlen)


def hp_filt(v: np.ndarray, fs: float, cutoff_freq: float = 0.01) -> np.ndarray:
    """Zero-phase high-pass the temporal components. Port of ``hpFilt.m``.

    3rd-order Butterworth, applied forwards and backwards (``filtfilt``). Useful when some
    components carry a very slow drift that swamps everything else.

    Returns float32, matching the MATLAB's ``single(...)`` cast.
    """
    v = np.asarray(v)
    b, a = butter(3, cutoff_freq / (fs / 2), btype="high")
    return _matlab_filtfilt(b, a, v.astype(np.float64), axis=-1).astype(np.float32)


def bandpass_filt(
    v: np.ndarray,
    fs: float,
    highpass: float | None = None,
    lowpass: float | None = None,
    order: int = 3,
    causal_highpass: bool = False,
) -> np.ndarray:
    """Butterworth band-pass / high-pass / low-pass of the temporal components.

    Filtering ``V`` filters every pixel, because reconstruction ``U @ V`` is linear in time — so
    this costs a filter over an ``(nSV, nFrames)`` array instead of the whole movie.

    Parameters
    ----------
    v : (nSV, nFrames)
    fs : frame rate in Hz.
    highpass : lower cutoff. ``None``, 0, or negative means no high-pass.
    lowpass : upper cutoff. ``None``, ``inf``, or >= Nyquist means no low-pass.
    order : Butterworth order (per direction).
    causal_highpass : run the *high-pass* one-pass forward (``sosfilt``) instead of zero-phase.
        The low-pass stays zero-phase either way; see the note below.

    Returns
    -------
    Filtered ``V``, same shape and dtype-promoted to float64. With neither cutoff set, a copy of
    the input.

    Notes
    -----
    Zero-phase (``filtfilt``) by default, unlike :func:`detrend_and_filt`: a movie viewer must not
    introduce a lag between the movie and the behavioral traces beside it, and there is no
    causality requirement when you already have the whole recording.

    ``causal_highpass=True`` exists for *event-locked* analysis, where zero-phase high-passing is
    actively misleading. A high-pass removes the local mean, so a sustained response after an
    event has to be balanced by an opposite deflection somewhere; run backwards as well as
    forwards, half of that lands *before* the event. On an opto session the pre-stimulus baseline
    then separates by laser power — an apparent "response" a full second before the laser fires.
    Filtering forwards only cannot move anything backwards in time, so the baseline stays put.

    Only the high-pass is made causal. A zero-phase *low-pass* also smears backwards, but only by
    its impulse width (tens of ms at the cutoffs used here) and, unlike the high-pass artifact,
    the amount does not grow with the size of the response — whereas making it causal *would*
    delay every measured peak latency. So the low-pass stays zero-phase, and with it the timing.

    When causal, the filter state is initialized to the steady state for each row's first sample
    (``sosfilt_zi``) rather than to zero. Otherwise a high-pass started from a large DC level
    rings for ~1/cutoff seconds — minutes, at 0.01 Hz — and the start of the recording is garbage.

    Uses second-order-sections rather than transfer-function coefficients. At the cutoffs that
    matter here — 0.01 Hz against a 35 Hz frame rate is a normalized frequency of 6e-4 — a
    ``b, a`` representation of a 3rd-order filter loses so much precision that the output can
    diverge, while SOS stays stable.
    """
    v = np.asarray(v, dtype=np.float64)
    if v.ndim != 2:
        raise ValueError(f"V must be (nSV, nFrames); got shape {v.shape}")
    nyquist = fs / 2.0

    hp = None if highpass is None or highpass <= 0 else float(highpass)
    lp = (
        None
        if lowpass is None or not np.isfinite(lowpass) or lowpass >= nyquist
        else float(lowpass)
    )

    if hp is None and lp is None:
        return v.copy()
    if hp is not None and hp >= nyquist:
        raise ValueError(f"highpass {hp} Hz is at or above Nyquist ({nyquist} Hz)")
    if hp is not None and lp is not None and hp >= lp:
        raise ValueError(f"highpass {hp} Hz must be below lowpass {lp} Hz")

    if causal_highpass and hp is not None:
        # Designed as separate stages so the two halves can be filtered differently; a single
        # band-pass design would force one choice on both.
        out = _sosfilt_causal(butter(order, hp / nyquist, btype="highpass", output="sos"), v)
        if lp is None:
            return out
        return sosfiltfilt(butter(order, lp / nyquist, btype="lowpass", output="sos"), out, axis=-1)

    if hp is not None and lp is not None:
        sos = butter(order, [hp / nyquist, lp / nyquist], btype="bandpass", output="sos")
    elif hp is not None:
        sos = butter(order, hp / nyquist, btype="highpass", output="sos")
    else:
        sos = butter(order, lp / nyquist, btype="lowpass", output="sos")
    return sosfiltfilt(sos, v, axis=-1)


def _sosfilt_causal(sos: np.ndarray, v: np.ndarray) -> np.ndarray:
    """One-pass ``sosfilt`` along the last axis, started from each row's own first sample.

    With zero initial conditions a high-pass sees a step from 0 to ``v[:, 0]`` at sample 0 and
    rings for roughly ``1 / cutoff`` seconds. Scaling ``sosfilt_zi`` by the first sample starts
    the filter already settled at that level, so the output begins near zero instead.
    """
    if v.shape[-1] == 0:
        return v.copy()
    zi = sosfilt_zi(sos)[:, np.newaxis, :] * v[np.newaxis, :, 0, np.newaxis]
    out, _ = sosfilt(sos, v, axis=-1, zi=zi)
    return out


def detrend_and_filt(v: np.ndarray, fs: float) -> np.ndarray:
    """Linear-detrend, notch out heartbeat, then high-pass. Port of ``detrendAndFilt.m``.

    Note this uses **causal** one-pass filtering (MATLAB ``filter``, not ``filtfilt``), so
    the output is phase-shifted relative to the input. That is what the production hemo
    pipeline applies to ``Vcorr``, so the port keeps it rather than silently "improving" it
    to zero-phase — changing it would shift every downstream latency measurement.
    """
    v = np.asarray(v, dtype=np.float64)
    highpass_cutoff = 0.01  # Hz
    heartbeat_bandstop = (9.0, 14.0)  # Hz

    b_hp, a_hp = butter(2, highpass_cutoff / (fs / 2), btype="high")
    b_heart, a_heart = butter(2, [f / (fs / 2) for f in heartbeat_bandstop], btype="bandstop")

    dv = detrend(v, axis=-1, type="linear")
    fv_heart = lfilter(b_heart, a_heart, dv, axis=-1)
    return lfilter(b_hp, a_hp, fv_heart, axis=-1)


def subsample_shift(v: np.ndarray, p: int, q: int) -> np.ndarray:
    """Delay a time series by ``p/q`` of a sample by linear interpolation.

    Port of ``SubSampleShift.m`` **as merged from cortex-lab's unmerged
    ``SubSampleShift_interp`` branch**: the older implementation used ``resample``, whose
    filtering could put a large error in the final sample that then became a big artifact
    after further filtering. Linear interpolation avoids that, and the original last sample
    is carried through verbatim rather than extrapolated.

    ``v`` is ``(nSV, nTimes)``; the shift is applied along time. Samples that fall past the
    end of the input are NaN (only reachable for ``p/q > 1``), except the very last, which
    is copied from the input.
    """
    v = np.asarray(v, dtype=np.float64)
    if v.ndim != 2:
        raise ValueError(f"V must be (nSV, nTimes); got shape {v.shape}")
    if p <= 0 or q <= 0:
        raise ValueError("p and q must be positive (negative shifts are not supported)")

    n = v.shape[1]
    src = np.arange(n, dtype=np.float64)
    query = src + (p / q)
    out = np.empty_like(v)
    for s in range(v.shape[0]):
        # left/right=nan reproduces interp1's default (no extrapolation).
        out[s] = np.interp(query, src, v[s], left=np.nan, right=np.nan)
    out[:, -1] = v[:, -1]
    return out


# --------------------------------------------------------------------------------------
# spatial binning
# --------------------------------------------------------------------------------------


def bin_image(image: np.ndarray, bin_factor: int) -> np.ndarray:
    """BxB spatial binning by box-filtering then decimating. Port of ``binImage.m``.

    ``image`` is ``(Ypix, Xpix)`` or ``(Ypix, Xpix, nFrames)``.

    This is deliberately *not* a block mean, and the difference is not cosmetic. The MATLAB
    convolves with a BxB box via ``conv2(..., 'same')`` and then takes every Bth sample
    starting at the first, which averages the window ``[i - (B - 1 - B//2), i + B//2]``:

    * ``B = 2`` — that window *is* the block ``[i, i+1]``, so binning by 2 does coincide with
      a block mean. This is a coincidence of the offset, not the general rule.
    * ``B >= 4`` — the window straddles the neighboring blocks (for ``B = 4`` it spans
      ``[i-1, i+2]``), so results differ substantially from a block mean, and out-of-range
      samples are treated as **zero** rather than renormalized, which biases the first and
      last row/column low. On the reference image ``B = 4`` gives 7.875 where a block mean
      gives 20.5.

    Output size is ``ceil(N / B)`` per axis: the final row/column is a partial, zero-padded
    window rather than being dropped.

    Faithfulness beats tidiness here — these values feed registration and QC comparisons
    against MATLAB-derived numbers, so the quirk is reproduced rather than fixed.
    """
    image = np.asarray(image)
    bin_factor = int(bin_factor)
    if bin_factor < 1:
        raise ValueError("bin_factor must be >= 1")
    if bin_factor == 1:
        return image.copy()
    squeeze = image.ndim == 2
    if squeeze:
        image = image[:, :, None]
    if image.ndim != 3:
        raise ValueError(f"image must be 2-D or 3-D; got shape {image.shape}")

    kern = np.ones(bin_factor, dtype=np.float64) / bin_factor
    off = bin_factor // 2
    ypix, xpix = image.shape[0], image.shape[1]

    out = []
    for f in range(image.shape[2]):
        frame = np.asarray(image[:, :, f], dtype=np.float64)
        # Separable box filter, 'full', then MATLAB's 'same' crop, then decimate.
        tmp = np.apply_along_axis(lambda col: np.convolve(col, kern, mode="full"), 0, frame)
        tmp = np.apply_along_axis(lambda row: np.convolve(row, kern, mode="full"), 1, tmp)
        same = tmp[off : off + ypix, off : off + xpix]
        out.append(same[::bin_factor, ::bin_factor])

    stacked = np.stack(out, axis=2).astype(image.dtype, copy=False)
    return stacked[:, :, 0] if squeeze else stacked
